name: Generate documentation

on:
  push:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g raml2html
    - run: raml2html raml_api_definition.yaml > api_documentation.html
    - run: git commit -am "Generate new html documentation"
    - run: |
       git config --global user.email "locascio.clement@gmail.com"
       git config --global user.name "ClemLcs"
       git push

